name: Do the daily tweaks

on:
  schedule:
  - cron:  '15 6 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'



jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check-out the repositories
      env:
         SECRET_SSH_KEY: ${{ secrets.VPP_DAILYCHECK_PRIVATE_SSH_KEY }}
         SECRET_GERRIT_KEY: ${{ secrets.FDIO_GERRIT_SECRET_KEY }}
      run: |
        sudo mkdir /run/user/$(id -u)
        sudo chown $(whoami) /run/user/$(id -u)
        sudo apt-get install -y --allow-downgrades libllvm6.0=1:6.0-1ubuntu2
        sudo apt-get install clang-format-6.0
        sudo apt-get update
        sudo apt-get install -y coreutils jq
        echo "$SECRET_SSH_KEY" >secret_ssh_key
        echo "$SECRET_GERRIT_KEY" >secret_gerrit_key
        chmod 600 secret_ssh_key
        chmod 600 secret_gerrit_key
        git clone https://github.com/FDio/vpp
        # only get the whatever is newest in FDIO, to save the waste of b/w for everyone
        (cd vpp; git remote add fdio.origin ssh://test4aiuortch@gerrit.fd.io:29418/vpp)
        ssh-agent bash -c 'ssh-add secret_gerrit_key; cd vpp; GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" git pull fdio.origin master'
        ssh-agent bash -c 'ssh-add secret_ssh_key; git clone git@github.com:vpp-dev/vpp-daily-tweaks.git'
    - name: Install vpp deps
      run: |
        cd vpp
        curl -Lo .git/hooks/commit-msg https://gerrit.fd.io/r/tools/hooks/commit-msg
        chmod +x .git/hooks/commit-msg
        make install-dep test-dep
        cd ..
        pwd
    - name: Do the needed tweaks
      run: |
        pwd
        LOGNAME="$(pwd)/vpp-daily-tweaks/RUN-LOG.md"
        echo "Started at $(date)" >>${LOGNAME}
        VPP_ROOT=$(pwd)/vpp"
        pushd tweaks
        for TWEAK_NAME in $(ls); do
            echo "Running tweak ${TWEAK_NAME}..." >>$LOGNAME
            # run each tweak on its own vpp branch
            (cd ${VPP_ROOT}; git checkout -b ayourtch-${TWEAK_NAME})
            pushd ${TWEAK_NAME}
            bash action
            popd
            # see if there is anything to submit
            pushd ${VPP_ROOT}
            CHANGES="$(git diff | wc -l)"
            if [ "$CHANGES" != "0" ]; then
                echo "Found something to submit after ${TWEAK_NAME}:" >>${LOGNAME}}
                git branch >> ${LOGNAME}
                git diff >>${LOGNAME}
            fi
            # reset back to master
            git checkout master
            popd
        done
        popd
        echo "Last done at $(date)" >>${LOGNAME}

    - name: Push the updates
      env:
         SECRET_SSH_KEY: ${{ secrets.VPP_DAILYCHECK_PRIVATE_SSH_KEY }}
      run: |
         cd vpp-daily-tweaks
         git config user.email "ayourtch+ghjobs@gmail.com"
         git config user.name  "Andrew Yourtchenko (ghjobs)"
         git add RUN-LOG.md || true
         git commit -a -m "Auto-update at $(date)"
         ssh-agent bash -c 'ssh-add ../secret_ssh_key; git push origin main'



